Add sonarqube to build (gh actions)

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -24,12 +24,15 @@ jobs:
           java-version: 1.8
       - name: Grant execute permission for gradlew
         run: chmod +x gradlew
-      - name: Execute jacocoTestReport
-        run: ./gradlew test jacocoTestReport && cp build/reports/jacoco/report.xml jacoco.xml || echo "Code coverage failed"
+      - name: Execute jacocoTestReport and Sonar
+        env:
+          SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
+        run: ./gradlew test jacocoTestReport sonarqube
+#        run: ./gradlew test jacocoTestReport && cp build/reports/jacoco/report.xml jacoco.xml || echo "Code coverage failed"
       - name: Build with Gradle
         run: ./gradlew build --refresh-dependencies --no-daemon --continue
-      - name: Push codeCoverage to Codecov
-        run: bash <(curl -s https://codecov.io/bash)
+#      - name: Push codeCoverage to Codecov
+#        run: bash <(curl -s https://codecov.io/bash)
 
   release:
     if: github.event_name == 'release'
@@ -42,12 +45,12 @@ jobs:
           java-version: 1.8
       - name: Grant execute permission for gradlew
         run: chmod +x gradlew
-      - name: Execute jacocoTestReport
-        run: ./gradlew test jacocoTestReport && cp build/reports/jacoco/report.xml jacoco.xml || echo "Code coverage failed"
+#      - name: Execute jacocoTestReport
+#        run: ./gradlew test jacocoTestReport && cp build/reports/jacoco/report.xml jacoco.xml || echo "Code coverage failed"
       - name: Build with Gradle
         run: ./gradlew build --refresh-dependencies --no-daemon --continue
-      - name: Push codeCoverage to Codecov
-        run: bash <(curl -s https://codecov.io/bash)
+#      - name: Push codeCoverage to Codecov
+#        run: bash <(curl -s https://codecov.io/bash)
       - name: Echo credentials
         run: echo "bintrayUser=${{secrets.BINTRAY_USER}}" >> gradle.properties
       - name: Echo credentials Key
